server:
  port: 9001
spring:
  application:
    name: consumer-feign-hysrtix2
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka
logging:
  level:
    root: INFO
    